name: fm_mahanama_nextgen
description: "Official FM Mahanama mobile and web client"

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  firebase_core: ^3.0.0
  firebase_analytics: ^11.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_crashlytics: ^4.0.0
  firebase_messaging: ^15.0.0
  firebase_performance: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
